name: gtsa
channels:
  - conda-forge
  - oggm
dependencies:
  - oggm
  - oggm-deps
  - awscli
  - s3fs
  - fsspec
  - gdown
  - aiohttp
  - numpy
  - scipy
  - matplotlib
  - contextily
  - statsmodels
  - pandas
  - geopandas
  - xarray
  - rioxarray
  - opencv
  - dask
  - folium
  - distributed
  - zarr
  - tqdm
  - pytest
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - pip
