name: gtsa
channels:
  - conda-forge
#   - oggm
dependencies:
  - awscli
  - s3fs
  - aiohttp
  - numpy
  - scipy
  - matplotlib
  - statsmodels
  - pandas
  - geopandas
  - xarray
  - rioxarray
  - opencv
  - dask
  - folium
  - distributed
  - zarr
  - tqdm
  - pip
  
#   - toml
#   - oggm
#   - oggm-deps

#   - jupyterlab

#   - holoviews
#   - geoviews
#   - datashader
#   - gdown
  # dev requirements
#   - pytest
#   pip
#   - pip:
#     - -e "git+https://github.com/GlacioHack/GeoUtils.git@main#egg=geoutils"
#     - -e "git+https://github.com/GlacioHack/xdem.git@main#egg=xdem"
