name: gtsa
channels:
  - conda-forge
dependencies:
  - awscli
  - s3fs
  - fsspec
  - gdown
  - aiohttp
  - numpy
  - scipy
  - matplotlib
  - pandas
  - geopandas
  - xarray
  - rioxarray
  - opencv
  - dask
  - folium
  - distributed
  - zarr
  - tqdm
  - pytest
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - hvplot
  - black
  - flake8
  - pip
